### ISSUE TITLE
throws error when using self signed certificate on pure array

### ISSUE THREAD

**Issue by rolandsteinmeyer** [PureStorage-OpenConnect/Monitoring#2]
urllib throws

InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

when using self signed certificate on pure array.

Suggest adding

logging.captureWarnings(True)

to def get_perf(self):

```
(...)
    def get_perf(self):
        """Gets hardware element status from flasharray."""
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
        logging.captureWarnings(True)
        fa = purestorage.FlashArray(self.endpoint, api_token=self.apitoken)
        fainfo = fa.get_hardware(component=self.component)
        fa.invalidate_cookie()
        return(fainfo)
(...)
```

**Comment by genegr** [comment]
Amended all the plugins with capturing warnings in the logger, as suggested.
