### ISSUE TITLE
syntax error in check_purefa_perf.py 

### ISSUE THREAD

**Issue by rolandsteinmeyer** [PureStorage-OpenConnect/Monitoring#3]
File "./check_purefa_perf.py", line 108
    nagiosplugin.Metric(mlabel + 'wbw', wbw, , min=0, context='wbw'),
                                             ^
SyntaxError: invalid syntax

**Comment by Strike3D** [comment]
To execute the script without problem remove the extra comma (like in the code paste in giithub) or add 'us' between the two commas:
nagiosplugin.Metric(mlabel + 'wbw', wbw, min=0, context='wbw')
OR
nagiosplugin.Metric(mlabel + 'wbw', wbw, 'us', min=0, context='wbw')

**Comment by genegr** [comment]
Fixed
