### ISSUE TITLE
Gathering hardware checking

### ISSUE THREAD

**Issue by bernah4** [PureStorage-OpenConnect/Monitoring#7]
Hi, is there any way to gather all hardware checkings in one check like an --all option with check_pure*_hw.py?

RSVP, and thx

**Comment by genegr** [comment]
Hi, although this is certainly possible, it would result in a quite long response string which is not what Nagios expects. The rationale a Nagios plugin should follow is to report a single status metric whilst a single output would require a proper suited metrics collector like Prometheus.
